### ISSUE TITLE
Database field to small

### ISSUE THREAD

**Issue by Hakker** [koel/docker#106]
I get this while trying to import my library in postgresql when running koel:sync

In Connection.php line 692:
                                                                               
  SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for  
   type character varying(191) (SQL: insert into "songs" ("id", "title", "len  
  gth", "track", "disc", "lyrics", "path", "mtime", "album_id", "artist_id",   
  "updated_at", "created_at") values (7c9798de87fc2598868f279eceb71dba, Suite  
   From The Trouble With Tribbles: Bartender Bit / They Quibble Over Quibble   
  / Kirk Out / Barrel of Trouble / Tribble Hooks Kirk / Poor Jonesy / A Matte  
  r of Pride / Come on Spock / Hissing Tribbles / Dead Heap, 319.11183333333,  
   2, 1, , /music/MP3/OST/Star Trek Series/Best of Star Trek - 30th Aniversar  
  y Special/Best of Star Trek Vol-1 - 02 - (TOS) [The Trouble With Tribbles]   
  Bartender Bit, They Quibble Over Quibble.mp3, 1621091693, 1359, 5067, 2021-  
  11-01 13:22:55, 2021-11-01 13:22:55))                                        
                                                                               

In Exception.php line 18:
                                                                               
  SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for  
   type character varying(191)                                                 
                                                                               

In PDOStatement.php line 112:
                                                                               
  SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for  
   type character varying(191)

My solution is simply to change the song field from varchar(191) tot varchar(500)

**Comment by phanan** [comment]
This shouldn't be an issue in later versions.
