### ISSUE TITLE
MySQL database access denied

### ISSUE THREAD

**Issue by xeruf** [koel/docker#128]
After [having no success with postgres](https://github.com/koel/docker/issues/117) I now tried mysql, but despite MYSQL_USER and PASSWORD being the same as the DB values for koel in `docker-compose.mysql.yml`, koel is unable to access the mysql database in the container:
```
SQLSTATE[HY000] [1045] Access denied for user 'koel'@'172.19.0.3' (using password: YES)
```
I have recreated the containers multiple times, and have no idea how to debug this...

**Comment by xeruf** [comment]
Solved, I did not recreate the containers fully as their volumes were kept...
https://stackoverflow.com/a/59839180/6723250

**Comment by Hyzual** [comment]
Hi @xeruf glad you found out the solution, thanks for posting it back here :)
Indeed volumes will keep the database configuration including users and passwords.
