### ISSUE TITLE
Can not initialise the docker stack

### ISSUE THREAD

**Issue by SylvainDx** [koel/docker#179]
Hello,

I use the docker-compose.mysql.yml file with just the password changes
and I cannot finish the koel:init because it cannot communicate with the db
<img width="649" alt="image" src="https://user-images.githubusercontent.com/88506082/226927502-4b429bde-d915-492f-b124-c261a1e64040.png">
I check installing ping on the koel's container and it can reach the db container.

**Comment by asdfzxcvbn** [comment]
i think i was having this issue with postgres, it should work fine if you use the mysql stack though

**Comment by asdfzxcvbn** [comment]
nevermind i just saw you're already using mysql, can you send your `docker-compose.yml`?

**Comment by essys** [comment]
I had the same problems.
Make sure that you use the same host information that you entered for DB_HOST in your Docker Compose file.
