### ISSUE TITLE
music path

### ISSUE THREAD

**Issue by PauFCB** [koel/docker#183]
HI, after go to the first run commands, it says: The absolute path to your media directory. If this is skipped (left blank) now, you can set it later via the web interface.
but even if I leave blank or put a path show me a error:  ERROR  The path does not exist or not readable. Try again?  
What can I do?

**Comment by pogora** [comment]
I had the same on my Synology NAS. It seems Koel does not have permissions to read my _/volume1/music_ folder. 
If I put the Music folder in ../docker/koel/music, it works. Thus must be permissions issue.

I found one way to make it work is give the music folder permissions: **everyone** read
But that is a bit iffy. What i'd like is a way to give a user permissions, like it's done with jellyfin. 
Much more secure that way.
