### ISSUE TITLE
Use STREAMING_METHOD=x-sendfile with docker

### ISSUE THREAD

**Issue by fluxor99232** [koel/docker#187]
Could anyone point me towards how I would get this to work? I can't get a single one of the thousands of .m4a files of mine to play. Also purchased the mobile app for iOS but it's completely dysfunctional for me like that. :-/

**Comment by phanan** [comment]
Have you tried https://docs.koel.dev/usage/streaming#streaming-methods?

**Comment by asdfzxcvbn** [comment]
> Have you tried https://docs.koel.dev/usage/streaming#streaming-methods?

i don't think it's very specific.. there are really no instructions on how to use the two alternative options.

can we configure koel's native webserver? or are the instructions for our reverse proxies? i don't even see x-accel mentioned in the example nginx config, and what if we want to use caddy?

i really would like to use the mobile app, however the documentation for streaming methods should really be improved

**Comment by phanan** [comment]
You're right that the documentation can always be improved. For the time being:

* Native PHP streaming works fine (the doc advised against it but it's been some time and things have changed for the better now)
* x-sendfile is an Apache module, so your web server needs to be Apache (with or without a proxy like nginx, doesn't matter)
* nginx supports x-accel. 
* Caddy etc: I don't have experience with them.

**Comment by phanan** [comment]
Closing as now it's a matter of documentation.
