### ISSUE TITLE
can't connetct last.fm

### ISSUE THREAD

**Issue by kroyoo** [koel/docker#62]
i see this: `https://docs.koel.dev/3rd-party.html#last-fm`
my configuration
`
APP_ENV=production
APP_DEBUG=false
APP_URL=https://koel.fungit.org/
ADMIN_NAME="Fungit"
ADMIN_EMAIL=koel@fungit.org
ADMIN_PASSWORD=1234566
APP_MAX_SCAN_TIME=600
MEMORY_LIMIT=
FORCE_HTTPS=true
LASTFM_API_KEY=9518c0b4b58b6adf5dceaebb2de40b56
LASTFM_API_SECRET=766d2fef444af4532f1e76f9f901f7f4
ALLOW_DOWNLOAD=true
`
when i click connect button in [profile](https://koel.fungit.org/#!/profile) . Whenever I change the API and key, it will be redirected to this address. `https://koel.fungit.org/web/lastfm/connect?api_token=1|t2JSsj2RUEMIoGy4vBHXTq9JZPT1KgNeQug30bT2`, this token Never change. This `https://koel.fungit.org/web/lastfm` URL also not found.

![image](https://user-images.githubusercontent.com/61957721/110798433-29793e80-8248-11eb-9336-cc74f5b39d32.png)

i try to fill homepage url or not, But it's the same thing

**Comment by kroyoo** [comment]
and can't generate JWT_SECRET
![image](https://user-images.githubusercontent.com/61957721/110799558-47936e80-8249-11eb-8951-6aded818af94.png)

**Comment by kroyoo** [comment]
> 
> 
> i see this: `https://docs.koel.dev/3rd-party.html#last-fm`
> my configuration
> `APP_ENV=production APP_DEBUG=false APP_URL=https://koel.fungit.org/ ADMIN_NAME="Fungit" ADMIN_EMAIL=koel@fungit.org ADMIN_PASSWORD=1234566 APP_MAX_SCAN_TIME=600 MEMORY_LIMIT= FORCE_HTTPS=true LASTFM_API_KEY=9518c0b4b58b6adf5dceaebb2de40b56 LASTFM_API_SECRET=766d2fef444af4532f1e76f9f901f7f4 ALLOW_DOWNLOAD=true`
> when i click connect button in [profile](https://koel.fungit.org/#!/profile) . Whenever I change the API and key, it will be redirected to this address. `https://koel.fungit.org/web/lastfm/connect?api_token=1|t2JSsj2RUEMIoGy4vBHXTq9JZPT1KgNeQug30bT2`, this token Never change. This `https://koel.fungit.org/web/lastfm` URL also not found.
> 
> ![image](https://user-images.githubusercontent.com/61957721/110798433-29793e80-8248-11eb-9336-cc74f5b39d32.png)
> 
> i try to fill homepage url or not, But it's the same thing

I find that the correct URL is "<domain>/lastfm/connect?api_token", not <domain>/web/lastfm/connect?api_token

![image](https://user-images.githubusercontent.com/61957721/111103886-cf1cfe00-8525-11eb-96c8-947060817a40.png)
![image](https://user-images.githubusercontent.com/61957721/111103926-e360fb00-8525-11eb-8794-7df38019f5fe.png)

**Comment by Hyzual** [comment]
Hi, were you able to do the lastfm integration ? From the last screenshot it looks like it worked

> and can't generate JWT_SECRET
It is expected, since [v5.0.0 of Koel](https://github.com/koel/koel/releases/tag/v5.0.0) there is no more JWT secret, so there is no longer a command to generate one.

**Comment by kroyoo** [comment]
> 
> 
> Hi, were you able to do the lastfm integration ? From the last screenshot it looks like it worked
> 
> > and can't generate JWT_SECRET
> 
> It is expected, since [v5.0.0 of Koel](https://github.com/koel/koel/releases/tag/v5.0.0) there is no more JWT secret, so there is no longer a command to generate one.
I find that the correct URL is "domain/lastfm/connect?api_token", not "domain/web/lastfm/connect?api_token''. 
The default URL is wrong("<domain>/web/lastfm/connect?api_token") . I need to use this address("<domain>/lastfm/connect?api_token") to connect to Last.fm

**Comment by Hyzual** [comment]
I could reproduce on a new installation. Indeed, the redirect URL with `/web/lastfm` is wrong and leads to 404.
Unfortunately it looks like I cannot help you further :confused:. I am not maintainer of koel, I only build the docker image. Would you please open an issue at https://github.com/koel/koel/issues so that the maintainers of Koel can change the redirect URL and fix the Lastfm integration ?

Also a side note: It looks like you have leaked your lastfm API key and secret in [this message](https://github.com/Hyzual/docker-koel/issues/62#issuecomment-799082313). I replaced them by `<REDACTED>` but you should revoke this key and create a new one. Anyone that has read this issue before could use the Lastfm API and impersonate you.

**Comment by kroyoo** [comment]
OK, thanks for your test. I also use the Docker version, and I'm not sure if there is any problem with the official compiled version.
