### ISSUE TITLE
Add pgsql support in Docker image

### ISSUE THREAD

**Issue by bubu8941** [koel/docker#69]
Hello ,
I couln not run `php artisan koel:init` because the docker  image miss psql database support.

Could you add the psql support to the image ? 

Thx by advance,

**Comment by bubu8941** [comment]
The missing in the docker file is the install of `postgresql-server-dev-11` Debian package which provides dependancies needed to make `docker-php-ext-install pdo pdo_pgsql` work correctly.

Because I want to follow your official releases, I add those actions in a postStart .exec.command in my K8s deploy as a workaroud

**Comment by Hyzual** [comment]
Hi, thanks for adding the details. I would welcome a pull request and could help with integrating it 🙂

**Comment by bubu8941** [comment]
Of course. 
However, i gave up Postgresql usage for this deploy (after viewing this bug  : https://github.com/koel/koel/issues/1286).
But when I'll succeed to have a stable result with my Kubernetes manifests, I'll make a PR ;).

For now I'm blocked with another issue withe PHP8 and getID3 Koel dependency which makes problems to sync music directory (getID3 lib behavior is buggy with PHP8)

**Comment by Hyzual** [comment]
Ok good luck with K8s, I don't know anything about it 😅.
I've seen that issue. I did not run into it myself so I had assumed koel could run on PHP8. I might revert the docker image back to PHP 7.4 if it helps 🤔

**Comment by bubu8941** [comment]
I built localy from the php 7.4 image and it works. :champagne: 
So I confirm it helps.

I'll send my kube stuff, (it needs to be a little cleaner ;) in a couple of days.

**Comment by bubu8941** [comment]
made this very quickly, hope it will help : 
https://github.com/bubu8941/koel_docker/tree/add-k8s

**Comment by Hyzual** [comment]
Closing as the latest version now supports PostgreSQL (see pr #78)
