### ISSUE TITLE
Cant Login after Completed the Setup. 

### ISSUE THREAD

**Issue by fscorrupt** [koel/docker#84]
Getting Error in Browser (Java is activated), im behind Traefik, do i have to edit something in Traefik?

why is the api request send via http? password and user is sent in cleartext.

![unknown](https://user-images.githubusercontent.com/45659314/123755522-43ed2b80-d8bc-11eb-876a-995980f3a873.png)

**Comment by FSCorrupt** [comment]
found the error, i had to add this to the end of **"/var/www/html/routes/web.php"**:

```
URL::forceRootUrl('https://koel.example.org');
URL::forceScheme('https');
```

Can you integrate this with Env?

Also the default memory limit in PHP is very low (512mb) cant even search for music because of that, maybe also make this available via a env?

Thanks in Advice!

**Comment by kimtiago** [comment]
Same here... your tip works for me!

**Comment by phanan** [comment]
`FORCE_HTTPS` in `.env` should work the same.
